---
kind: pipeline
type: kubernetes
name: Build-arm64

steps:
  - name: nagiosserver
    image: plugins/docker
    settings:
      repo: registry-private.support.tools/k8s-nagios/server
      registry: registry-private.support.tools
      dockerfile: server/Dockerfile
      context: server/
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest
      username:
        from_secret: registry-username
      password:
        from_secret: registry-password
  - name: dellpowerconnect
    image: plugins/docker
    settings:
      repo: registry-private.support.tools/k8s-nagios/workers/dellpowerconnect
      registry: registry-private.support.tools
      dockerfile: workers/dellpowerconnect/Dockerfile
      context: workers/dellpowerconnect/
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest
      username:
        from_secret: registry-username
      password:
        from_secret: registry-password
  - name: linuxserver
    image: plugins/docker
    settings:
      repo: registry-private.support.tools/k8s-nagios/workers/linuxserver
      registry: registry-private.support.tools
      dockerfile: workers/linuxserver/Dockerfile
      context: workers/linuxserver/
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest
      username:
        from_secret: registry-username
      password:
        from_secret: registry-password

node_selector:
  beta.kubernetes.io/arch: arm64

---
kind: pipeline
type: kubernetes
name: Build-amd64

steps:
  - name: nagiosserver
    image: plugins/docker
    settings:
      repo: registry-private.support.tools/k8s-nagios/server
      registry: registry-private.support.tools
      dockerfile: server/Dockerfile
      context: server/
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest
      username:
        from_secret: registry-username
      password:
        from_secret: registry-password
  - name: dellpowerconnect
    image: plugins/docker
    settings:
      repo: registry-private.support.tools/k8s-nagios/workers/dellpowerconnect
      registry: registry-private.support.tools
      dockerfile: workers/dellpowerconnect/Dockerfile
      context: workers/dellpowerconnect/
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest
      username:
        from_secret: registry-username
      password:
        from_secret: registry-password
  - name: linuxserver
    image: plugins/docker
    settings:
      repo: registry-private.support.tools/k8s-nagios/workers/linuxserver
      registry: registry-private.support.tools
      dockerfile: workers/linuxserver/Dockerfile
      context: workers/linuxserver/
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest
      username:
        from_secret: registry-username
      password:
        from_secret: registry-password        

node_selector:
  beta.kubernetes.io/arch: amd64
